ci: disable source code downloading for CI
* ci: disable source code downloading for CI

* ci(vpc): disable source code downloading for CI

We have currently issues with downloading the source code from the Ubuntu mirrors in our CI.
To mitigate the issues we opt-out the source downloading.

Separate commit for VPC.

Signed-off-by: Tobias Giese <tgiese@nvidia.com>

* ci: disable source code downloading for CI

We have currently issues with downloading the source code from the Ubuntu mirrors in our CI.
To mitigate the issues we opt-out the source downloading.

Signed-off-by: Tobias Giese <tgiese@nvidia.com>

Based on release-v25.7@fd7072e811a9502c2ff1f936368051ff50082b05

diff --git a/Dockerfile.bfb-registry b/Dockerfile.bfb-registry
--- a/Dockerfile.bfb-registry
+++ b/Dockerfile.bfb-registry
@@ -29,12 +29,17 @@ RUN mkdir -p /nginx
 
 # Move source code to a directory
 WORKDIR /workspace
-RUN mkdir src && \
-    cd src && \
-    cp /workspace/${tengine_version}.zip . && \
-    apt-get source --download-only ${PACKAGES} && \
-    cd /workspace && \
-    tar -cf source-code.tar src
+ARG PACKAGE_SOURCES
+# First, create a dummy source-code.tar file to avoid copy failures.
+RUN touch /workspace/source-code.tar
+RUN test "${PACKAGE_SOURCES}" = "false" || ( \
+      mkdir src && \
+      cd src && \
+      cp /workspace/${tengine_version}.zip . && \
+      apt-get source --download-only ${PACKAGES} && \
+      cd /workspace && \
+      tar -cf source-code.tar src \
+    )
 
 # Stage 2: Create final image based on distroless
 FROM nvcr.io/nvidia/doca/dpf_containers:1.0.2-ubuntu22.04-distroless AS distroless
